langauge: generic
dist: trusty
sudo: required

branches:
  only:
  - master

matrix:
  fast_finish: true
  include:
    - os: linux
      name: Debian
      dist: trusty
    - os: linux
      name: Build

oservices:
  - docker

git:
  quiet: true

before_script:
  - git clone -q --depth=1 https://github.com/radare/radare2
  - ( cd radare2 && sys/debian.sh /usr ) > /dev/null
  - cp -f radare2/sys/debian/rad*/*.deb /tmp
  - git clean -xdf
  - ( cd radare2 && sys/install.sh /usr ) > /dev/null
#  - cd radare2 && ./configure --prefix=/usr > /dev/null && make -j4 > /dev/null && sudo make install > /dev/null

script:
  - |
    set -e
    r2 -v
    case "$TRAVIS_JOB_NAME" in
    Build)
      ./configure --prefix=/usr
      make
      sudo make install
      # r2 -qcq frida://0
      ;;
    Debian)
      pwd
      ./configure --prefix=/usr > /dev/null
      make -C dist/debian
      wget -q https://github.com/probonopd/uploadtool/raw/master/upload.sh
      cp -f /tmp/*.deb dist/debian
      compgen -G "dist/debian/*.deb" > /dev/null && bash upload.sh dist/debian/*.deb
      # compgen -G "/tmp/*.pkg" > /dev/null && bash upload.sh /tmp/*.pkg
      ;;
    esac
